# Generated by Django 2.1.2 on 2018-10-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20181027_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_one_board', models.CharField(max_length=10000)),
                ('player_two_board', models.CharField(max_length=10000)),
                ('current_player', models.CharField(max_length=100)),
                ('winning_player', models.CharField(max_length=100)),
                ('hits_taken', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='dbsession',
            name='game_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
